version: '3.8'

services:
  # backend:
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   command: npm run start:debug
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge