/**
 * @packageDocumentation
 * @module api.functional.articles.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ArticleDto } from "../../../../api/articles/articles.controller";

/**
 * @controller ArticleControllerUser.getAllUser
 * @path GET /articles/user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllUser(
    connection: IConnection,
): Promise<getAllUser.Output> {
    return PlainFetcher.fetch(
        connection,
        {
            ...getAllUser.METADATA,
            path: getAllUser.path(),
        } as const,
    );
}
export namespace getAllUser {
    export type Output = Primitive<Array<ArticleDto>>;

    export const METADATA = {
        method: "GET",
        path: "/articles/user",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/articles/user`;
    }
}